/*
 * Vectors.c
 *
 *  Created on: May 2, 2012
 *      Author: CongTH
 */
#include <hidef.h> /* for EnableInterrupts macro */
volatile int isr_idx = 0;		/* Stores the identifier of the interrupt that was issued */

interrupt 1U void ISR1() {	   isr_idx = 1;      HALT;  }	//SPARE
interrupt 2U void ISR2() {     isr_idx = 2;      HALT;  }	//TRAP
interrupt 3U void ISR3() {     isr_idx = 3;      HALT;  }	//SWI
interrupt 4U void ISR4() {     isr_idx = 4;      HALT;  }	//SYS
interrupt 5U void ISR5() {     isr_idx = 5;      HALT;  }	//Machine Exception
interrupt 6U void ISR6() {     isr_idx = 6;      HALT;  }	//Reserved
interrupt 7U void ISR7() {     isr_idx = 7;      HALT;  }	//Reserved
interrupt 8U void ISR8() {     isr_idx = 8;      HALT;  }	//Spurious Interrupt
interrupt 9U void ISR9() {     isr_idx = 9;      HALT;  }	//XIRQ interrupt
interrupt 10U void ISR10() {   isr_idx = 10;     HALT;  }	//IRQ interrupt
interrupt 11U void ISR11() {   isr_idx = 11;     HALT;  }	//RTI
interrupt 12U void ISR12() {   isr_idx = 12;     HALT;  }	//TIM0 chan0
interrupt 13U void ISR13() {   isr_idx = 13;     HALT;  }	//TIM0 chan1
//interrupt 14U void ISR14() {   isr_idx = 14;     HALT;  }	//TIM0 chan2

//interrupt 15U void ISR15() {   isr_idx = 15;     HALT;  }	//TIM0 chan3

interrupt 16U void ISR16() {   isr_idx = 16;     HALT;  }	//Reserved
interrupt 17U void ISR17() {   isr_idx = 17;     HALT;  }	//Reserved
interrupt 18U void ISR18() {   isr_idx = 18;     HALT;  }	//Reserved
interrupt 19U void ISR19() {   isr_idx = 19;     HALT;  }	//Reserved
interrupt 20U void ISR20() {   isr_idx = 20;     HALT;  }	//TIM0 timer overflow
interrupt 21U void ISR21() {   isr_idx = 21;     HALT;  }	//Reserved
interrupt 22U void ISR22() {   isr_idx = 22;     HALT;  }	//Reserved
interrupt 23U void ISR23() {   isr_idx = 23;     HALT;  }	//SPI0
//interrupt 24U void ISR24() {   isr_idx = 24;     HALT;  }	//SCI0
interrupt 25U void ISR25() {   isr_idx = 25;     HALT;  }	//SCI1
interrupt 26U void ISR26() {   isr_idx = 26;     HALT;  }	//Reserved
interrupt 27U void ISR27() {   isr_idx = 27;     HALT;  }	//Reserved
interrupt 28U void ISR28() {   isr_idx = 28;     HALT;  }	//ADC0 Error
interrupt 29U void ISR29() {   isr_idx = 29;     HALT;  }	//ADC0 Conv Seq Abort
interrupt 30U void ISR30() {   isr_idx = 30;     HALT;  }	//ADC0 Conv Complete
interrupt 31U void ISR31() {   isr_idx = 31;     HALT;  }	//Oscillator Status
interrupt 32U void ISR32() {   isr_idx = 32;     HALT;  }	//PLL Lock
interrupt 33U void ISR33() {   isr_idx = 33;     HALT;  }	//Reserved
interrupt 34U void ISR34() {   isr_idx = 34;     HALT;  }	//Reserved
interrupt 35U void ISR35() {   isr_idx = 35;     HALT;  }	//RAM error
interrupt 36U void ISR36() {   isr_idx = 36;     HALT;  }	//Reserved
interrupt 37U void ISR37() {   isr_idx = 37;     HALT;  }	//Reserved
interrupt 38U void ISR38() {   isr_idx = 38;     HALT;  }	//FLASH error 
interrupt 39U void ISR39() {   isr_idx = 39;     HALT;  }	//FLASH command
interrupt 40U void ISR40() {   isr_idx = 40;     HALT;  }	//CAN0 wake-up
interrupt 41U void ISR41() {   isr_idx = 41;     HALT;  }	//CAN0 error
interrupt 42U void ISR42() {   isr_idx = 42;     HALT;  }	//CAN0 receive
interrupt 43U void ISR43() {   isr_idx = 43;     HALT;  }	//CAN0 transmit
interrupt 44U void ISR44() {   isr_idx = 44;     HALT;  }	//Reserved
interrupt 45U void ISR45() {   isr_idx = 45;     HALT;  }	//Reserved
interrupt 46U void ISR46() {   isr_idx = 46;     HALT;  }	//LINPHY over-current
interrupt 47U void ISR47() {   isr_idx = 47;     HALT;  }	//BATS supply voltage monitor
interrupt 48U void ISR48() {   isr_idx = 48;     HALT;  }	//GDU desaturation error
interrupt 49U void ISR49() {   isr_idx = 49;     HALT;  }	//GDU voltage limit detected
interrupt 50U void ISR50() {   isr_idx = 50;     HALT;  }	//Reserved
interrupt 51U void ISR51() {   isr_idx = 51;     HALT;  }	//Reserved
interrupt 52U void ISR52() {   isr_idx = 52;     HALT;  }	//Reserved
interrupt 53U void ISR53() {   isr_idx = 53;     HALT;  }	//Reserved
interrupt 54U void ISR54() {   isr_idx = 54;     HALT;  }	//Port S
interrupt 55U void ISR55() {   isr_idx = 55;     HALT;  }	//Reserved
interrupt 56U void ISR56() {   isr_idx = 56;     HALT;  }	//ADC1 Error
interrupt 57U void ISR57() {   isr_idx = 57;     HALT;  }	//ADC1 Conv Seq Abort
interrupt 58U void ISR58() {   isr_idx = 58;     HALT;  }	//ADC1 Conv Complete
interrupt 59U void ISR59() {   isr_idx = 59;     HALT;  }	//Reserved
interrupt 60U void ISR60() {   isr_idx = 60;     HALT;  }	//Port P
interrupt 61U void ISR61() {   isr_idx = 61;     HALT;  }	//EVDD1 Over-current
interrupt 62U void ISR62() {   isr_idx = 62;     HALT;  }	//Low Voltage Interrupt (LVI)
interrupt 63U void ISR63() {   isr_idx = 63;     HALT;  }	//Autonomous Periodical Interrupt (API)
interrupt 64U void ISR64() {   isr_idx = 64;     HALT;  }	//High Temperature
interrupt 65U void ISR65() {   isr_idx = 65;     HALT;  }	//Reserved
interrupt 66U void ISR66() {   isr_idx = 66;     HALT;  }	//Port AD
interrupt 67U void ISR67() {   isr_idx = 67;     HALT;  }	//PTU Reload Overrun
interrupt 68U void ISR68() {   isr_idx = 68;     HALT;  }	//PTU Trigger 0 Error
interrupt 69U void ISR69() {   isr_idx = 69;     HALT;  }	//PTU Trigger 1 Error
interrupt 70U void ISR70() {   isr_idx = 70;     HALT;  }	//PTU Trigger 0 Done
interrupt 71U void ISR71() {   isr_idx = 71;     HALT;  }	//PTU1 Trigger 1 Done
interrupt 72U void ISR72() {   isr_idx = 72;     HALT;  }	//Reserved
interrupt 73U void ISR73() {   isr_idx = 73;     HALT;  }	//Reserved
interrupt 74U void ISR74() {   isr_idx = 74;     HALT;  }	//Reserved
interrupt 75U void ISR75() {   isr_idx = 75;     HALT;  }	//PMF Reload A
interrupt 76U void ISR76() {   isr_idx = 76;     HALT;  }	//PMF Reload B
interrupt 77U void ISR77() {   isr_idx = 77;     HALT;  }	//PMF Reload C
interrupt 78U void ISR78() {   isr_idx = 78;     HALT;  }	//PMF Fault
interrupt 79U void ISR79() {   isr_idx = 79;     HALT;  }	//PMF Reload Overrun
interrupt 80U void ISR80() {   isr_idx = 80;     HALT;  }	//Reserved
interrupt 81U void ISR81() {   isr_idx = 81;     HALT;  }	//Reserved
interrupt 82U void ISR82() {   isr_idx = 82;     HALT;  }	//Reserved
interrupt 83U void ISR83() {   isr_idx = 83;     HALT;  }	//Reserved
interrupt 84U void ISR84() {   isr_idx = 84;     HALT;  }	//Reserved
interrupt 85U void ISR85() {   isr_idx = 85;     HALT;  }	//Reserved
interrupt 86U void ISR86() {   isr_idx = 86;     HALT;  }	//Reserved
interrupt 87U void ISR87() {   isr_idx = 87;     HALT;  }	//Reserved
interrupt 88U void ISR88() {   isr_idx = 88;     HALT;  }	//Reserved
interrupt 89U void ISR89() {   isr_idx = 89;     HALT;  }	//Reserved
interrupt 90U void ISR90() {   isr_idx = 90;     HALT;  }	//Reserved
interrupt 91U void ISR91() {   isr_idx = 91;     HALT;  }	//Reserved
interrupt 92U void ISR92() {   isr_idx = 92;     HALT;  }	//Reserved
interrupt 93U void ISR93() {   isr_idx = 93;     HALT;  }	//Reserved
interrupt 94U void ISR94() {   isr_idx = 94;     HALT;  }	//Reserved
interrupt 95U void ISR95() {   isr_idx = 95;     HALT;  }	//Reserved
interrupt 96U void ISR96() {   isr_idx = 96;     HALT;  }	//Reserved
interrupt 97U void ISR97() {   isr_idx = 97;     HALT;  }	//Reserved
interrupt 98U void ISR98() {   isr_idx = 98;     HALT;  }	//Reserved
interrupt 99U void ISR99() {   isr_idx = 99;     HALT;  }	//Reserved
interrupt 100U void ISR100() { isr_idx = 100;    HALT;  }	//Reserved
interrupt 101U void ISR101() { isr_idx = 101;    HALT;  }	//Reserved
interrupt 102U void ISR102() { isr_idx = 102;    HALT;  }	//Reserved
interrupt 103U void ISR103() { isr_idx = 103;    HALT;  }	//Reserved
interrupt 104U void ISR104() { isr_idx = 104;    HALT;  }	//Reserved
interrupt 105U void ISR105() { isr_idx = 105;    HALT;  }	//Reserved
interrupt 106U void ISR106() { isr_idx = 106;    HALT;  }	//Reserved
interrupt 107U void ISR107() { isr_idx = 107;    HALT;  }	//Reserved
interrupt 108U void ISR108() { isr_idx = 108;    HALT;  }	//Reserved
interrupt 109U void ISR109() { isr_idx = 109;    HALT;  }	//Reserved
interrupt 110U void ISR110() { isr_idx = 110;    HALT;  }	//Reserved
interrupt 111U void ISR111() { isr_idx = 111;    HALT;  }	//Reserved
interrupt 112U void ISR112() { isr_idx = 112;    HALT;  }	//Reserved
interrupt 113U void ISR113() { isr_idx = 113;    HALT;  }	//Reserved
interrupt 114U void ISR114() { isr_idx = 114;    HALT;  }	//Reserved
interrupt 115U void ISR115() { isr_idx = 115;    HALT;  }	//Reserved
interrupt 116U void ISR116() { isr_idx = 116;    HALT;  }	//Reserved
interrupt 117U void ISR117() { isr_idx = 117;    HALT;  }	//Reserved
interrupt 118U void ISR118() { isr_idx = 118;    HALT;  }	//Reserved
interrupt 119U void ISR119() { isr_idx = 119;    HALT;  }	//Reserved
interrupt 120U void ISR120() { isr_idx = 120;    HALT;  }	//Reserved
interrupt 121U void ISR121() { isr_idx = 121;    HALT;  }	//Reserved
interrupt 122U void ISR122() { isr_idx = 122;    HALT;  }	//Reserved
interrupt 123U void ISR123() { isr_idx = 123;    HALT;  }	//Reserved


